[workspace]
authors = ["Ogarit <tiagomarquesdados@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "diverse_data_visualization"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.0,<3.15"
matplotlib = ">=3.10.7,<4"
